drop user watch@localhost;
drop database nwatch;
create database nwatch;
use nwatch;

CREATE TABLE USERS (
    USERID int NOT NULL AUTO_INCREMENT,
    FNAME varchar(60),
    LNAME varchar(60),
    HOUSE varchar(120),
    USERNAME varchar(20) UNIQUE,
    PASSWORD varchar(20),
    PRIMARY KEY (USERID)
);

CREATE TABLE LISTS (
    LISTID int NOT NULL AUTO_INCREMENT,
    WLIST varchar(15),
    MACWLIST varchar(17),
    MACBLIST varchar(17),
    BLIST varchar(15),
    USERID int NOT NULL,
    PRIMARY KEY (LISTID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);



INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('admin','password123','JACK','OTOOL','64 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('POP','kjsdfkjsd','JACK','OTOOL','66 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('jibby','ksd','JACK','OTOOL','646 T fdgfdg dfg HE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('wank','poo','JACK','OTOOL','64 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('josshh','pass','JACK','OTOOL','64 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('ur maaa','ddd','JACK','OTOOL','64 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('dfdfd','password123','JACK','OTOOL','64 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('sss','kjsdfkjsd','JACK','OTOOL','66 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('fff','ksd','JACK','OTOOL','646 T fdgfdg dfg HE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('waeenk','poo','JACK','OTOOL','64 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('wewe','pass','JACK','OTOOL','64 THE GREEN');
INSERT INTO USERS(USERNAME,PASSWORD,FNAME,LNAME,HOUSE) VALUES ('ptig maaa','ddd','JACK','OTOOL','64 THE GREEN');

INSERT INTO LISTS(WLIST,USERID) VALUES ('d01ds',4);
INSERT INTO LISTS(WLIST,USERID) VALUES ('344h3h',4);
INSERT INTO LISTS(WLIST,USERID) VALUES ('6617KE191',4);
INSERT INTO LISTS(WLIST,USERID) VALUES ('kkdfdfddd',4);
INSERT INTO LISTS(BLIST,USERID) VALUES ('MMssss',4);
INSERT INTO LISTS(BLIST,USERID) VALUES ('MMdksds',4);
INSERT INTO LISTS(BLIST,USERID) VALUES ('lksf34ke',4);

CREATE USER 'watch'@'localhost' IDENTIFIED BY '3342234Pp&^';
GRANT ALL PRIVILEGES ON nwatch.USERS TO 'watch'@'localhost';
GRANT ALL PRIVILEGES ON nwatch.LISTS TO 'watch'@'localhost';

